In [1]:
import numpy as np
import time

In [22]:
# Load dataset
data=np.genfromtxt("students.csv",
delimiter=",",skip_header=1)
print("Original Dataset:\n")
print(data)

Original Dataset:

[[ 1. 78. 85. 90.]
 [ 2. 88. 79. 76.]
 [ 3. 92. 91. 89.]
 [ 4. 65. 70. 72.]
 [ 5. 81. 84. 80.]
 [ 6. 74. 68. 77.]
 [ 7. 90. 95. 93.]
 [ 8. 69. 73. 70.]
 [ 9. 85. 88. 86.]
 [10. 76. 80. 79.]]


In [23]:
# Array creation
print("\nArray Shape:",data.shape)


Array Shape: (10, 4)


In [24]:
# Indexing
print("\nFirst Student Record:")
print(data[-1])


First Student Record:
[10. 76. 80. 79.]


In [25]:
# Slicing
print("\nFirst Five Students:")
print(data[:5])


First Five Students:
[[ 1. 78. 85. 90.]
 [ 2. 88. 79. 76.]
 [ 3. 92. 91. 89.]
 [ 4. 65. 70. 72.]
 [ 5. 81. 84. 80.]]


In [26]:
# Mathematical Operations
marks=data[:,1:]
print("\nAdd 5 bonus marks:")
print(marks+5)


Add 5 bonus marks:
[[ 83.  90.  95.]
 [ 93.  84.  81.]
 [ 97.  96.  94.]
 [ 70.  75.  77.]
 [ 86.  89.  85.]
 [ 79.  73.  82.]
 [ 95. 100.  98.]
 [ 74.  78.  75.]
 [ 90.  93.  91.]
 [ 81.  85.  84.]]


In [27]:
# Axis-wise operations
print("\nSubject-wise Total:")
print(np.sum(marks,axis=0))


Subject-wise Total:
[798. 813. 812.]


In [28]:
# Statistical operations
print("Mean:-",np.mean(data))
print("Median:-",np.median(data))
print("Maximum marks:-",np.max(data))
print("Minimum marks:-",np.min(data))
print("Standard Deviation:-",np.std(data))

Mean:- 61.95
Median:- 76.5
Maximum marks:- 95.0
Minimum marks:- 1.0
Standard Deviation:- 33.39532152862134


In [29]:
# Reshaping
numbers=np.arange(1,13)
print("\nOriginal Array:",numbers)
print("\nReshaped Array:-",numbers.reshape(3,4))


Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped Array:- [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [30]:
# Broadcasting
print("\nBroadcasting (+10 Marks):",marks+10)


Broadcasting (+10 Marks): [[ 88.  95. 100.]
 [ 98.  89.  86.]
 [102. 101.  99.]
 [ 75.  80.  82.]
 [ 91.  94.  90.]
 [ 84.  78.  87.]
 [100. 105. 103.]
 [ 79.  83.  80.]
 [ 95.  98.  96.]
 [ 86.  90.  89.]]


In [34]:
# save numpy array
np.save("students_marks.npy",marks)
print("\nArray Saved Succesfully!")


Array Saved Succesfully!


In [35]:
# Load numpy array
loaded=np.load("students_marks.npy")
loaded

array([[78., 85., 90.],
       [88., 79., 76.],
       [92., 91., 89.],
       [65., 70., 72.],
       [81., 84., 80.],
       [74., 68., 77.],
       [90., 95., 93.],
       [69., 73., 70.],
       [85., 88., 86.],
       [76., 80., 79.]])

In [36]:
# Performance comparison
python_list=list(range(1000000))
numpy_array=np.arange(1000000)
start=time.time()
python_result=[x*2 for x in python_list]
python_time=time.time() - start
start=time.time()
numpy_result=numpy_array * 2
numpy_time=time.time() - start
print("\nPerformance Comparison")
print("Python List Time:",python_time)
print("Numpy array time:",numpy_time)


Performance Comparison
Python List Time: 0.21904325485229492
Numpy array time: 0.004503488540649414
